springdoc:
  api-docs:
    path: /diti/swagger.html
    groups:
      enabled: true
  swagger-ui:
    path: /diti/swagger.html
    enabled: true
    doc-expansion: none
  cache:
    disabled: true
  override-with-generic-response: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  packages-to-scan: com.diti.core.domain.controller