version: '3'

volumes:
  uniqon_main_data:
    external:
      name: uniqon_main_data

networks:
  uniqon_network:
    driver: bridge

services:
  uniqon_mysql:
    restart: on-failure
    image: 'mysql:latest'
    container_name: 'uniqon_mysql'
    environment:
      MYSQL_DATABASE: uniqon
      MYSQL_ROOT_PASSWORD: ssafyuniqon
      TZ: Asia/Seoul
    networks:
      - uniqon_network
    volumes:
      - uniqon_main_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    
  uniqonSpringServer:
    restart: on-failure
    depends_on:
      - uniqon_mysql
    image: 'kmr5326/c201-backend:latest'
    container_name: uniqonSpringServer
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://uniqon_mysql:3306/uniqon'
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ssafyuniqon
    networks:
      - uniqon_network
  
  uniqonNodejsServer:
    restart: on-failure
    depends_on:
      - uniqonSpringServer
    image: 'jihyon/uniqon-nodejs:latest'
    container_name: uniqonNodejsServer
    environment:
      SPRING_SERVER_URI: http://uniqonSpringServer:8080
    ports:
      - '5000:4000'
    networks:
      - uniqon_network